apiVersion: batch/v1
kind: Job
metadata:
  name: jira-sync-${SYNC_ID}
  labels:
    app: jira-sync
    sync-type: ${SYNC_TYPE}
    sync-id: ${SYNC_ID}
    managed-by: jira-sync-scheduler
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 600  # 10 minutes for single issue sync
  template:
    metadata:
      labels:
        app: jira-sync
        sync-type: ${SYNC_TYPE}
        sync-id: ${SYNC_ID}
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: sync-worker
        image: jira-sync:latest
        imagePullPolicy: IfNotPresent
        command: ["./jira-sync"]
        args: 
        - "sync"
        - "--issues=${TARGET}"
        - "--repo=/workspace/repo"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: git-repo
          mountPath: /workspace/repo
        - name: config
          mountPath: /etc/jira-sync
          readOnly: true
        - name: credentials
          mountPath: /etc/jira-sync/secrets
          readOnly: true
        env:
        - name: JIRA_BASE_URL
          valueFrom:
            secretKeyRef:
              name: jira-credentials
              key: base-url
        - name: JIRA_PAT
          valueFrom:
            secretKeyRef:
              name: jira-credentials
              key: token
        - name: SYNC_JOB_ID
          value: ${SYNC_ID}
        - name: LOG_LEVEL
          value: "INFO"
        - name: SPIKE_SAFE_MODE
          value: "true"
      volumes:
      - name: git-repo
        persistentVolumeClaim:
          claimName: git-repo-pvc
      - name: config
        configMap:
          name: jira-sync-config
      - name: credentials
        secret:
          secretName: jira-credentials
          defaultMode: 0400