apiVersion: v1
kind: ConfigMap
metadata:
  name: jira-sync-api-config
  namespace: jira-sync-v040
  labels:
    app: jira-sync-api
    version: v0.4.0
data:
  config.yaml: |
    api:
      port: 8080
      host: "0.0.0.0"
      enable_authentication: false
      enable_rate_limit: true
      rate_limit_per_minute: 100
      read_timeout: "30s"
      write_timeout: "30s"
      idle_timeout: "120s"
      log_level: "INFO"
      enable_cors: true
      allowed_origins: ["*"]
    
    jobs:
      namespace: "jira-sync-v040"
      image: "jira-sync:latest"
      default_timeout: "600"
      cleanup_policy: "delete"
      
    kubernetes:
      in_cluster: true
      
    sync:
      safe_mode: true
      default_parallelism: 2
      default_batch_size: 50