apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira-sync-api
  namespace: jira-sync-v040
  labels:
    app: jira-sync-api
    version: v0.4.0
    component: api-server
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: jira-sync-api
      version: v0.4.0
  template:
    metadata:
      labels:
        app: jira-sync-api
        version: v0.4.0
        component: api-server
      annotations:
        config-hash: "placeholder"  # Will be updated during deployment
    spec:
      serviceAccountName: jira-sync-api
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: api-server
        image: localhost/jira-sync-api:latest
        imagePullPolicy: Never
        command: ["/bin/api-server"]
        args:
        - "serve"
        - "--enable-jobs"
        - "--namespace=jira-sync-v040"
        - "--image=localhost/jira-cdc-git:latest"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: config
          mountPath: /etc/jira-sync
          readOnly: true
        - name: credentials
          mountPath: /etc/jira-sync/secrets
          readOnly: true
        env:
        - name: JIRA_BASE_URL
          valueFrom:
            secretKeyRef:
              name: jira-credentials
              key: base-url
        - name: JIRA_EMAIL
          valueFrom:
            secretKeyRef:
              name: jira-credentials
              key: email
        - name: JIRA_PAT
          valueFrom:
            secretKeyRef:
              name: jira-credentials
              key: token
        - name: LOG_LEVEL
          value: "INFO"
        - name: LOG_FORMAT
          value: "json"
        - name: SPIKE_SAFE_MODE
          value: "true"
        - name: API_PORT
          value: "8080"
        - name: API_HOST
          value: "0.0.0.0"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
      - name: config
        configMap:
          name: jira-sync-api-config
      - name: credentials
        secret:
          secretName: jira-credentials
          defaultMode: 0400
      restartPolicy: Always
      terminationGracePeriodSeconds: 30