apiVersion: v1
kind: ServiceAccount
metadata:
  name: jira-sync-api
  namespace: jira-sync-v040
  labels:
    app: jira-sync-api
    version: v0.4.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jira-sync-api
  labels:
    app: jira-sync-api
    version: v0.4.0
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jira-sync-api
  labels:
    app: jira-sync-api
    version: v0.4.0
subjects:
- kind: ServiceAccount
  name: jira-sync-api
  namespace: jira-sync-v040
roleRef:
  kind: ClusterRole
  name: jira-sync-api
  apiGroup: rbac.authorization.k8s.io