apiVersion: v1
kind: Service
metadata:
  name: jira-sync-api
  namespace: jira-sync-v040
  labels:
    app: jira-sync-api
    version: v0.4.0
    component: api-server
spec:
  type: ClusterIP
  selector:
    app: jira-sync-api
    version: v0.4.0
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
---
# NodePort service for external access during demo
apiVersion: v1
kind: Service
metadata:
  name: jira-sync-api-external
  namespace: jira-sync-v040
  labels:
    app: jira-sync-api
    version: v0.4.0
    component: api-server-external
spec:
  type: NodePort
  selector:
    app: jira-sync-api
    version: v0.4.0
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
    nodePort: 30080  # Fixed port for easy demo access