{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "jira-sync-operator.fullname" . }}
  namespace: {{ include "jira-sync-operator.namespace" . }}
  labels:
    {{- include "jira-sync-operator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "jira-sync-operator.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}